package-lock.json, package.json, public/mockServiceWorker.js, src/App.tsx, src/layouts/RootLayout.tsx, src/main.tsx, src/mocks/browser.ts, src/mocks/handlers/AuthHandlers.ts, src/mocks/handlers/ChannelHandler.ts, src/mocks/handlers/SearchHandlers.ts, src/mocks/handlers/UserHandler.ts, src/pages/CreateCourse.tsx, src/pages/Test.tsx, src/pages/test/AuthTest.tsx, src/pages/test/ChannelTest.tsx, src/pages/test/UserTest.tsx
mocks/handler
1. Channel, Auth, UserHandler, SearchHandler 파일 추가
2. 민혁님 보시고 해당 폴더에 파일 추가하시면 됩니다!
3. 참고: https://mswjs.io/docs/best-practices/structuring-handlers
mocks broswer
1. allHandlers 배열에 import한 handler 추가
=> [6 feature mock api 테스트 코드 작성-2] mocks/handler 파일 분리, browser import

src/api/api.ts, src/components/HeaderIcon.tsx, src/layouts/RootLayout.tsx, src/pages/Notification.tsx
알림창 기능 구현
/page/notification.tsx 추가
api.tsx에 notification api추가
개인 JWT를 받아서 나오는 알림창은 미구현
상단 로고
HeaderIcon.tsx추가
RootLayout에 HeaderIcon추가
=> ✨  Feature: 알림창 기능 구현, 상단 로고, 알림창, 햄버거 이미지 추가

src/components/main/allCourse/AllCourseCardItem.tsx, src/components/main/allCourse/AllCourseCards.tsx, src/components/main/allCourse/AllCourseHeader.tsx, src/components/main/allCourse/AllCourseSortToggle.tsx, src/components/main/allCourse/SearchInputFeild.tsx, src/pages/Main.tsx, src/types/mainfeed/props.d.ts
=> [merge / 20-feature-main-feed-퍼블리싱] 💄 add: 메인 피드 화면 퍼블리싱 완료 (추후 리펙토링 필요)

src/App.tsx, src/components/InputField.tsx, src/components/Root/HeaderIcon.tsx, src/components/Root/Nav.tsx, src/hooks/useCookie.ts, src/pages/Login.tsx, src/pages/Signup.tsx
회원가입 할 때 받는 닉네임, 이메일, 비민번호의 유효성을 검사하면 화면에 나타냄
로그인 했을 때 알림 버튼을 누르면 알림페이지로 이동하고
로그인 하지 않았을 경우 로그인 페이지로 이동하게 구현
=> 72 feature 로그인 과 회원가입 유효성 검사, 로그인 유무에 따른 알림 버튼의 페이지 이동 구현

src/components/Root/Nav.tsx
=> [merge / 94-feature-코스생성탭에서-하단탭-사용x ]✨ feat: 코스생성탭에서 하단탭사용X

package-lock.json, package.json, src/App.tsx, src/api/postApi.ts, src/components/main/MainAllCourse.tsx, src/components/main/allCourse/AllCourseCardItem.tsx, src/components/main/allCourse/AllCourseCards.tsx, src/components/main/courseContent/CourseContentDoc.tsx, src/main.tsx, src/pages/CourseContent.tsx, src/stores/mainFeedStore.ts, src/types/mainfeed/props.d.ts, src/types/post.d.ts, src/utills/main/formatingDate.ts
=> [merge /  81-feature-메인-피드-상세-페이지-코멘트-영역-퍼블리싱] ✨ feat: 메인 피드 상세페이지 API 연결

src/api/axios.ts, src/api/commentApi.ts, src/components/main/courseContent/CourseContentDoc.tsx, src/components/main/courseContent/commentArea/CommentInputArea.tsx, src/components/main/courseContent/commentArea/CommentList.tsx, src/components/main/courseContent/commentArea/courseContentCommentArea.tsx, src/utills/Auth/getTokenWithCloser.ts, src/utills/main/fomatter.ts
=> [merge / 107-feature-메인-피드-상세-페이지-api-연동 ] ✨ feat: axiosInstance 토큰값 수정

src/components/createMyCourseMain/flow2/mapview/MapDisplay.tsx, src/pages/Login.tsx
로그인페이지 css 수정
코스 생성 페이지 css 수정
=> 로그인페이지 , 코스 생성 페이지 css 수정

src/api/postApi.ts, src/api/userApi.ts, src/components/createMyCourseMain/flow2/mapview/MapDisplay.tsx, src/components/viewMycourse/ViewMyAllCourse.tsx
=> 123 feature 마이 코스 필터링

src/stores/useInfoStore.ts, src/stores/useLikesStore.ts
- 유저 정보 지역 속성 추가
-  프로필 사진 새로고침 시 날라가는 오류 수정
=> [merge/125-feature-마이페이지-댓글-api-및-삭제-기능-구현] ✨ feat: 유저정보 지역 속성 추가

src/api/api.ts, src/components/utills/Validate.tsx, src/components/viewMycourse/MyCourseCards.tsx, src/components/viewMycourse/MyCourseSearch.tsx, src/components/viewMycourse/ViewMyAllCourse.tsx, src/pages/Login.tsx, src/pages/Signup.tsx
viewmycourse-검색-기능-logintsx-signuptsx-공통함수-utils로-통합
=> viewmycourse-검색-기능-logintsx-signuptsx-공통함수-utils로-통합

src/api/commentApi.ts, src/api/userApi.ts, src/components/My/MyComment.tsx, src/components/My/MyComment/MyCommentCardItem.tsx, src/components/My/MyComment/MyCommentCards.tsx, src/components/My/MyLike.tsx, src/components/My/MypageCards/MypageCardItem.tsx, src/components/My/MypageCards/MypageCards.tsx, src/components/My/MypageMyCourse.tsx, src/components/My/MypageProfile.tsx, src/components/My/userInfo/UserInfoForm.tsx, src/components/My/userInfo/UserInfoInput.tsx, src/components/My/userInfo/UserInfoProfile.tsx, src/components/My/userInfo/UserInfoUpdate.tsx, src/components/utills/SearchBar.tsx, src/stores/useCommentsStore.ts, src/stores/useInfoStore.ts
- 마이페이지 마이코스 API 연동 및 검색 필터 데이터 연동
- 유저 아이디 전역 상태 관리로 저장
=> [merge/135-feature-마이페이지-라이크-및-검색바-api-연결] ✨ feat: 마이페이지 마이코스 API 연동 및 검색 기능 구현

src/App.tsx, src/components/createMyCourseMain/CreateMyCourseFlowButton.tsx, src/components/createMyCourseMain/flow2/mapview/MapDisplay.tsx, src/components/viewMycourse/MyCourseSearch.tsx, src/pages/NotFound.tsx, src/pages/createcourse/CreateMycourse.tsx, src/pages/createcourse/MapView.tsx, src/pages/createcourse/SelectTag.tsx
없는 url 404페이지로 디동하도록 notfound 페이지 추가, 
맵 검색 리스트 fennel에 데이터 추가 및 스타일 수정
=> 404페이지 추가, 맵 검색 리스트 fennel에 데이터추가 및 스타일 수정

src/components/createMyCourseMain/flow2/mapview/MapDisplay.tsx, src/pages/createcourse/CreateMycourse.tsx, src/pages/createcourse/MapView.tsx
검색한 맵 리스트들의 리스트 선택 중복 방지 처리 
리스트를 선택 하지 않고 다음페이지 이동 방지 처리
=> 검색한-맵-리스트들-선택-리스트-중복-방지-처리, 리스트 선택 하지 않고 다음페이지 이동 방지

src/api/commentApi.ts, src/components/My/MyComment.tsx, src/components/My/MyComment/MyCommentCardItem.tsx, src/components/My/MyComment/MyCommentCards.tsx, src/components/My/MyLike.tsx, src/components/My/MypageCards/MypageCardItem.tsx, src/components/My/MypageCards/MypageCards.tsx, src/components/My/MypageMyCourse.tsx, src/components/utills/SearchBar.tsx, src/stores/useCommentsStore.ts, src/stores/useInfoStore.ts, src/stores/useLikesStore.ts, src/stores/useMyCourseStore.ts, src/types/mainfeed/props.d.ts
- 좋아요 누른 게시물 불러오기 ✅
- 댓글 / 마이코스 / 라이크 ) 좋아요 데이터 연동 ✅
- 댓글 목록 불러오기 ✅
- 댓글 삭제 기능✅
- 검색 기능 연결 ✅
- 댓글 최신순으로 정렬 ✅
- 검색바 로직 수정 ✅
- 클릭 시 해당 게시물의 상세 페이지로 이동 ✅
=> [merge/144-feature-마이페이지-댓글-api-연동-및-검색-기능-연동] ✨ feat: 마이페이지 댓글/좋아요 API 연동 및 검색 기능 연결 구현

src/components/category/Feed.tsx, src/components/main/allCourse/AllCourseCardItem.tsx, src/utills/main/fomatter.ts
=> [merge /152-feature-상세페이지-location-card-카테고리별-아이콘-적용] 🐛 fix: allCourseCardItem 필수 데이터 입력받지 않았을 경우 validation check

package-lock.json, package.json, src/App.tsx, src/api/api.ts, src/components/My/userInfo/UserInfoUpdate.tsx, src/components/createMyCourseMain/flow2/mapview/MapDisplay.tsx, src/components/main/courseContent/LikeButton.tsx, src/components/main/courseContent/commentArea/CommentInputArea.tsx, src/pages/CreateChannel.tsx, src/pages/test/ChannelTest.tsx
=> alert창 커스텀 alert창으로 변경

src/components/My/MypageUserInfo.tsx, src/components/createMyCourseMain/flow2/mapview/MapDisplay.tsx, src/components/viewMycourse/ViewMyCourseHeader.tsx, src/pages/MyPage.tsx, src/pages/Notification.tsx, src/pages/createcourse/SelectTag.tsx, src/pages/createcourse/ViewMycourse.tsx, src/types/plaist.d.ts, tsconfig.json
맵 재랜더링 수정
로그인 후 접근가능한 페이지를 url로 접근 했을 시 로그인 페이지로 이동
마이코스
http://localhost:5173/my-course-builder
SelectTag.tsx 
http://localhost:5173/my-course-builder?my-funnel-app.step=코스상세입력
http://localhost:5173/my-course-builder?my-funnel-app.step=장소선택
http://localhost:5173/my-course-builder?my-funnel-app.step=게시글작성
http://localhost:5173/my-course-builder?my-funnel-app.step=완료
마이페이지
http://localhost:5173/my-page
MyPage.tsx
http://localhost:5173/user-info MypageUserInfo.tsx  
알림
http://localhost:5173/notification
Notification.tsx   /login?page=my-course-builder/viewer
=> 접근 권한 없는 페이지 로그인 페이지로 이동, 맵 재랜더링 수정

src/components/My/MypageCards/MypageCardItem.tsx, src/components/My/MypageProfile.tsx, src/components/My/MypageUserInfo.tsx, src/components/My/userInfo/UserInfo.tsx, src/components/My/userInfo/UserInfoProfile.tsx, src/components/My/userInfo/UserInfoUpdate.tsx, src/components/Root/HeaderIcon.tsx, src/components/Root/Nav.tsx
- 상단바, 하단바 수정
- 마이페이지 CSS 수정 및 로직 정리
=> [merge/193-refactor-마이페이지-api-채널-필터링] ♻️ refact: 상단바, 하단바 및 마이페이지 수정

src/components/My/MyComment.tsx, src/components/My/MyLike.tsx, src/components/My/MypageMyCourse.tsx, src/components/main/MainAllCourse.tsx, src/components/main/allCourse/AllCourseHeader.tsx, src/components/utills/SearchBar.tsx, src/components/viewMycourse/ViewMyAllCourse.tsx, src/pages/main/MainFeed.tsx
- 검색바 컴포넌트 타입 수정
- 검색 컴포넌트 다중 searchKey 및 twmerge 추가
- 메인피드 검색바 컴포넌트 추가 및 연결
- 마이코스 검색바 컴포넌트 추가 및 연결
=> [merge/230-feature-메인피드마이코스-검색바-컴포넌트-추가-및-연동] ✨ faet: 메인피드/마이코스 검색바 수정 및 컴포넌트 추가삽입

src/api/postApi.ts, src/api/userApi.ts, src/components/My/MyLike.tsx, src/components/My/userInfo/UserInfoForm.tsx, src/components/My/userInfo/UserInfoProfile.tsx, src/components/My/userInfo/UserInfoUpdate.tsx, src/stores/useCommentsStore.ts, src/stores/useInfoStore.ts, src/stores/useLikesStore.ts, src/stores/useMyCourseStore.ts
- 오류 처리 ( 상위 호출로 )
- 디버깅 코드 제거
=> [merge/250-refactor-마이페이지-오류-로직-수정] ♻️ refact : 오류 처리 수정 및 디버깅 코드 제거

src/stores/useLikesStore.ts
=> [merge/256-bug-전체적인-테스트] ✨ feat: 마이페이지 최신순으로 정렬

src/api/postMyCourse.ts, src/components/viewMycourse/MyCourseCards.tsx, src/components/viewMycourse/ViewMyAllCourse.tsx, src/pages/Signup.tsx, src/pages/main/CourseContent.tsx
마이 코스 상세페이지에서 수정 여러번 하면 코스 삭제되는 오류 수정
=> ✨ 마이 코스 상세페이지에서 수정 여러번 하면 코스 삭제되는 오류 수정

README.md
=> [merge /  276-deploy-readmemd-시연-gif-작성] README.md 파일 수정

package.json, src/Router.tsx, src/components/category/Feed.tsx, src/components/main/bestCourse/BestCourseCardItem.tsx, src/components/main/courseContent/commentArea/CommentInputArea.tsx, src/components/main/courseContent/commentArea/CommentList.tsx, src/main.tsx, src/pages/OtherUserInfo.tsx, src/pages/createcourse/CreateMycourse.tsx, src/stores/main/comment/useCommentStore.ts, src/types/mainfeed/props.d.ts, src/utills/Auth/setCookie.ts, src/utills/main/fomatter.ts, src/utills/mycourse/findValueByKeyInSpot.ts, src/utills/mycourse/setPostTitle.ts
타입 에러 해결 
ts 파일에서의 잘못된 store 문법 수정
=> 타입 에러 해결, ts 파일에서의 잘못된 store 문법 수정
